README.md
add database adapter to db config file
=> db adapter

scripts/Phalcon/Builder/Model.php
Notice: Undefined index  schema in \Phalcon\Builder\Model.php on line 341
=> was error for PostgreSql

scripts/Phalcon/Commands/Builtin/Controller.php
"Model -> Controller" in Controller ::$_possibleParameters
=> typo fixed for controller generator

scripts/Phalcon/Version/Item.php
7ce962c reverted #211 fix. Doing it again.
=> Redo @zeromodule's bugfix (last migration always applying).

scripts/Phalcon/Builder/Model.php
Detect hasMany and belongsTo relationships automatically and add them to the initialize function.
=> Automatic relationship detection

scripts/Phalcon/Builder/Model.php
Model Commad: Resolved generation of relations if table name is used in other database.
=> Issue #339

scripts/Phalcon/Builder/AllModels.php, scripts/Phalcon/Commands/Builtin/AllModels.php
Add the parameter --mapcolumn to all-models/create-all-models
=> Add mapcolumn to all-models

scripts/Phalcon/Builder/AllModels.php, scripts/Phalcon/Builder/Model.php, scripts/Phalcon/Commands/Builtin/AllModels.php, scripts/Phalcon/Commands/Builtin/Model.php
In commands model and all-models added abstract option to generate Abstract Class
=> NFR Issue #342

scripts/Phalcon/Builder/Controller.php, scripts/Phalcon/Commands/Builtin/Controller.php
-Clean up commits.
-Added output command to controller
-Added fallback to relative directory using realpath and php directory constant
=> Fixed Controller Directory, and clean up previous attempts

scripts/Phalcon/Web/Tools/controllers/ModelsController.php
Litter fix to correct include 'schema' in model generate
=> Fix on webtools for generate model

scripts/Phalcon/Builder/Project/Modules.php, templates/project/modules/index.php, templates/project/modules/routes.php, templates/project/modules/services.php
Allows modules to have different namespace, retrieves from className instead of standard namespace created by dev tools.
=> Better module routes, cleanups

scripts/Phalcon/Builder/Model.php
Collapse commit and use real path
=> Cleanups, use realpath

scripts/Phalcon/Commands/Builtin/Migration.php
Added detection to support module projects.
=> Migration detect modules/single directory

scripts/Phalcon/Commands/Builtin/Migration.php, scripts/Phalcon/Migrations.php, scripts/Phalcon/Mvc/Model/Migration.php
=> Added skip/reset auto increment command

scripts/Phalcon/Builder/Model.php
Also fixed bug which deletes previous phpdoc when use `--force` for models.
**Note: Possible the same issue still exists for other generators.**
=> Fixed #276

scripts/Phalcon/Builder/AllModels.php, scripts/Phalcon/Builder/Component.php, scripts/Phalcon/Builder/Controller.php, scripts/Phalcon/Builder/Model.php, scripts/Phalcon/Builder/Path.php, scripts/Phalcon/Builder/Project.php, scripts/Phalcon/Builder/Scaffold.php, scripts/Phalcon/Commands/Builtin/AllModels.php, scripts/Phalcon/Commands/Command.php, scripts/Phalcon/Generator/Snippet.php, scripts/Phalcon/Web/Tools/controllers/ControllerBase.php, templates/project/cli/services.php, templates/project/micro/services.php, templates/project/modules/index.php, templates/project/modules/services.php, templates/project/modules/variables.json, templates/project/simple/services.php
=> Path Component

ide/2.0.0/Phalcon/paginator/AdapterInterface.php, scripts/Phalcon/Builder/Path.php
=> Fixed #434

scripts/Phalcon/Generator/Snippet.php, scripts/Phalcon/Migrations.php, scripts/Phalcon/Mvc/Model/Migration.php, scripts/Phalcon/Version/Item.php
=> Add feature to reverse a migration

README.md
Removed because of the long lack of feedback for #109
Will be added back as needed.
=> Removed PEAR instruction

ide/2.0.7/Phalcon/Di.php, ide/2.0.8/Phalcon/Di.php
See https://github.com/phalcon/cphalcon/pull/10983
=> Fixed return for Phalcon\Di::get

scripts/Phalcon/Commands/Command.php
```php
if (strpos($parameter, "=") !== false) {
// ...
} else {
if (strpos($parameter, "=") !== false) {
// ...
} else {
// ...
}
}
```
=> Refactored `Phalcon\Commands\Command` slightly

scripts/Phalcon/Commands/Builtin/Migration.php, scripts/Phalcon/Migrations.php
Much clearer way to store migrations log. Automatically solve problems with deployment to a number of servers which use same db servers.
Also some PSR1/PSR2 cosmetic changes.
=> Options to store information about last migration in database

scripts/Phalcon/Mvc/Model/Migration.php
Phalcon migration Generate/Run error with Postgresql #419 fixed.
only crash on Postgresql
=> fix #419 (branch 2.0.x)

scripts/Phalcon/Mvc/Model/Migration.php
Phalcon migration Generate/Run error with Postgresql #419 fixed.
only crash on Postgresql
=> fix #419 (branch 2.1.x)

scripts/Phalcon/Commands/Builtin/Migration.php, scripts/Phalcon/Migrations.php, scripts/Phalcon/Version/ItemCollection.php
* introduced "logInDb" and "migrationsTsBased" config variables which may be overridden by cli options
* fixed very initial migration numbering in timestamped migration scheme
=> timestamped migrations fix and new config variables

scripts/Phalcon/Migrations.php
Rollback strong to the specified version.
=> Fix Double Rollback Migration

scripts/Phalcon/Builder/Model.php, scripts/Phalcon/Commands/Builtin/Model.php, scripts/Phalcon/Generator/Snippet.php, scripts/Phalcon/Utils.php
Add "camelize" flag to the model generator. Simple add --camelize and model`s properies will be named  in lowerCamelCase style.
=> Add "camelize" flag to the model generator

scripts/Phalcon/Builder/Model.php
Fixes my last PR #641 with require_once instead of require. That will save some resource loading.  Sorry for that =/
=> changed to require_once on Model.php

scripts/Phalcon/Mvc/Model/Migration.php
Respect null values while processing a `*.dat` file
=> Respect null values in batch insert

templates/project/cli/services.php, templates/project/micro/services.php, templates/project/modules/services.php, templates/project/simple/services.php
These variables aren't declared in the services file anymore.
=> Remove old comment about global variables being declared in file.

templates/project/cli/config.php, templates/project/modules/Module_web.php, templates/project/modules/bootstrap_cli.php, templates/project/modules/bootstrap_web.php, templates/project/modules/config.ini, templates/project/modules/config.php, templates/project/modules/loader.php, templates/project/modules/services.php, templates/project/simple/config.ini, templates/project/simple/config.php, templates/project/simple/services.php
I'm leaving the Volt setup as it is in the `simple` module and the `modules` template is getting some custom work to demonstrate how to change the Volt compiled path.
=> Improvements

scripts/Phalcon/Migrations.php
=> Roilled back MIGRATION_LOG_TABLE constant

templates/project/micro/config.php, templates/project/modules/config.php, templates/project/simple/config.php
Modified: Retrieved correct base file path in config.php(s) under both Apache/Nginx and Command Line Tool.
=> Modified: Retrieved correct base file path in config.php(s) under both Apache/Nginx and Command Line Tool.

scripts/Phalcon/Migrations.php, scripts/Phalcon/Script.php, scripts/Phalcon/Version/IncrementalItem.php, scripts/Phalcon/Web/Tools/Traits/DatabaseAware.php, scripts/Phalcon/Web/Tools/controllers/ControllerBase.php, scripts/Phalcon/Web/Tools/controllers/MigrationsController.php, scripts/Phalcon/Web/Tools/controllers/ModelsController.php, scripts/Phalcon/Web/Tools/controllers/ScaffoldController.php
* Fixed `IncrementalItem::$_versionStamp`
* Fixed `IncrementalItem::$_parts`
* Cleaned WebTools `ControllerBase`
* Improved `Migrations::generate`
-----------------------------
Refs: #768
=> Migrations fixes

scripts/Phalcon/Migrations.php, scripts/Phalcon/Mvc/Model/Migration.php
=> Fixed dump data on migration

scripts/Phalcon/Migrations.php
HI,
I was having a issue rolling back 2 migrations. So the Scenario:
2 migrations:
Test1:
```
class StatementTypeMigration_1473782767490667 extends Migration
{
/**
* Run the migrations
*
* @return void
*/
public function up()
{
echo 'UP1' . PHP_EOL;
}
/**
* Reverse the migrations
*
* @return void
*/
public function down()
{
echo 'DOWN1' . PHP_EOL;
}
}
```
and Test2:
```
class StatementTypeMigration_1473782773155414 extends Migration
{
/**
* Run the migrations
*
* @return void
*/
public function up()
{
echo 'UP2' . PHP_EOL;
}
/**
* Reverse the migrations
*
* @return void
*/
public function down()
{
echo 'DOWN2' . PHP_EOL;
}
}
```
Doing migration run i get UP1 and UP2. Rolling back both, i get DOWN2 and DOWN2. So let's analyse run method.
It was trying to run:
InitialVersion => test2 | …
=> fixed migrations - when running back more than one migration

phalcon
@nueko https://github.com/phalcon/phalcon-devtools/blob/3.0.x/phalcon.sh#L92-L98
=> Remove wrong alias

bootstrap/autoload.php
=> Improved PTOOLSPATH check

scripts/Phalcon/Migrations.php
I merged the previous pull request with 3.0.x branch.
=> Bugfixes for the migrations

composer.json
Hello!
* Link to issue: #931
Thanks
=> Fixed vendor binaries

templates/module/Module.php
=> fixed module.php bug

.travis.yml, README.md, ide/stubs/Phalcon/Security.php, ide/stubs/Phalcon/mvc/controller/BindModelInterface.php, tests/lint.sh
Hello!
* Link to issue: #942
This pull request affects the following components:
=> Introduced recursive PHP syntax check (lint)

templates/project/micro/app.php
=> fix 404 bug.

README.md
Hello!
* Link to issue: https://github.com/phalcon/phalcon-devtools/issues/941
Explain how to solve a Git installation problem where a `"phalcon: command not found"` appears while trying to symlink phalcon to the system.
Thanks
=> Explain how to solve a Git installation problem

ide/stubs/Phalcon/mvc/Model.php
=> Fixed Phalcon\Mvc\Model::find return type name (error in namespace) 

ide/1.3.0/Phalcon/Mvc/Model.php
Added the parameters to **hasOne**, **belongsTo**, **hasMany** and **hasManyToMany**
Hello!
Thanks
=> Added information in model relations

ide/1.3.0/Phalcon/Validation/ValidatorInterface.php
Added the type to validator
Hello!
Thanks
=> Added the type to validator

templates/project/modules/bootstrap_web.php, templates/project/simple/index.php
Remove blank spaces and line breaks in order to reduce the response
size.
=> Minify response

composer.json, phalcon.php, scripts/Phalcon/Commands/Builtin/Console.php
Hello!
* new feature
Added a runtime developer console like tinker from artisan.
Thanks
=> Add a runtime developer console like tinker from artisan

phalcon.bat
=> Fix initialization home directory in Windows batch file.

scripts/Phalcon/Migrations.php
Hello!
This fixes a small bug with column width in migrations list.
Thanks
=> Fixed migrations list column width

scripts/Phalcon/Builder/Project.php, scripts/Phalcon/Utils/FsUtils.php, scripts/Phalcon/Web/Tools.php
Hello!
* Link to issue: #1007
Small description of change: fixed problem creation/deleting css and js files while enable/disable webtools and while create new project
Thanks
=> fix problem with creation css and js files

scripts/Phalcon/Web/Tools/Controllers/MigrationsController.php
Hello!
Small description of change: in MigrationsController.php file add exceprion output
Thanks
=> add show exception message in MigrationsController

resources/js/dashboard.js, scripts/Phalcon/Web/Tools/Controllers/MigrationsController.php, scripts/Phalcon/Web/Tools/Views/migrations/generate.volt
Hello!
Small description of change: Migration data doesn't generated with migration
Thanks
=> Problem with migration data which generated in browser

scripts/Phalcon/Db/Adapter/Pdo/MysqlExtended.php, scripts/Phalcon/Db/Dialect/MysqlExtended.php, scripts/Phalcon/Mvc/Model/Migration.php
Hello!
* Link to issue: #556
Small description of change: fix bug with addition foreign keys
Thanks
=> fix issue with addForeingKey

scripts/Phalcon/Builder/Model.php, scripts/Phalcon/Commands/Builtin/Model.php
Hello!
* Link to issue: #663
**In raising this pull request, I confirm the following :**
For proper creating model when table name has hyphen
Thanks
=> Create model with hyphen in table name

scripts/Phalcon/Db/Adapter/Pdo/PostgresqlExtended.php, scripts/Phalcon/Db/Dialect/PostgresqlExtended.php, scripts/Phalcon/Mvc/Model/Migration.php
Hello!
Added describeReferences() methods in adapter and dialect for postgresql DB
Thanks
=> Added describeReferences method in postgresql DB

scripts/Phalcon/Builder/AllModels.php, scripts/Phalcon/Builder/Model.php
Hello!
* Link to issue: #821
Improving `build` to generate model.
Thanks
=> Improve generating model issue #821

.travis.yml, codeception.yml, composer.json, tests/_bootstrap.php, tests/_ci/setup_dbs.sh, tests/_data/schemas/postgresql/dump.sql, tests/_support/Helper/Db/Dialect/PostgresqlTrait.php, tests/_support/Module/UnitTest.php, tests/shim.php, tests/unit.suite.yml, tests/unit/Db/Adapter/Pdo/PostgresqlTest.php, tests/unit/_bootstrap.php
Hello!
Added UnitTest for describeReferences method in Postgresql DB
Thanks
=> UnitTest for describeReferences method in Postgresql DB

scripts/Phalcon/Commands/Builtin/Project.php
Hello!
* Link to issue: #972
Fixed problem with project name when it's creating.
Thanks
=> Fixed problem with projects name

scripts/Phalcon/Builder/Project.php
Hello!
* Link to issue: #1048
Added a reminder after creating project.
Thanks
=> Added a reminder when project was created

scripts/Phalcon/Migrations.php, scripts/Phalcon/Mvc/Model/Migration.php, tests/console/RunUpDownMigrationCept.php
Hello!
* Link to PR: https://github.com/phalcon/phalcon-devtools/pull/617
Checking migration versions upgrade or downgrade
Thanks
=> Improve additional checking migration versions

scripts/Phalcon/Devtools/Version.php
Hello!
fix devtools version number from the cli output
Thanks
=> fix devtools version number output

scripts/Phalcon/Commands/Command.php, scripts/Phalcon/Commands/CommandsListener.php
Hello!
* Type: code quality, small improvement
I've removed redundant slash in config file path check, and I've added a slash to 'directory' option (`.phalcon` file/dir check in `\Phalcon\Commands\CommandsListener::beforeCommand()` ) 
Thanks
=> Some paths handle improvements

scripts/Phalcon/Console/OptionParserTrait.php, scripts/Phalcon/Console/OptionStack.php, tests/unit/Console/OptionStackTest.php
Hello!
* Link to issue:-
Added class to work with options
Thanks
=> Added Option class, work with received options

scripts/Phalcon/Console/OptionParserTrait.php, scripts/Phalcon/Migrations.php
Hello!
Moved `getVersionNameGeneratingMigration()` to `OptionStackTrait`. This method wasn't static but called statically. 
Thanks
=> Moved generating migration name

templates/project/micro/views/404.phtml, templates/project/micro/views/404.volt, templates/project/micro/views/index.phtml, templates/project/micro/views/index.volt, templates/project/modules/views/index.phtml, templates/project/modules/views/index.volt, templates/project/simple/views/index.phtml, templates/project/simple/views/index.volt
Hello!
* Link to issue: #903
Add favicon link to template projects
Thanks
=> Add favicon link to template

.travis.yml, phpstan.neon, scripts/Phalcon/Access/Policy/Ip.php, scripts/Phalcon/Bootstrap.php, scripts/Phalcon/Builder/Model.php, scripts/Phalcon/Commands/Builtin/Model.php, scripts/Phalcon/Commands/DotPhalconMissingException.php, scripts/Phalcon/Elements/Element.php, scripts/Phalcon/Mvc/Controller/Base.php, scripts/Phalcon/Mvc/Model/Migration.php, scripts/Phalcon/Mvc/View/NotFoundListener.php, scripts/Phalcon/Utils/SystemInfo.php, scripts/Phalcon/Version/ItemCollection.php, scripts/Phalcon/Version/TimestampedItem.php, scripts/Phalcon/Web/Tools/Controllers/ControllersController.php, scripts/Phalcon/Web/Tools/Controllers/ErrorController.php, scripts/Phalcon/Web/Tools/Controllers/MigrationsController.php, scripts/Phalcon/Web/Tools/Controllers/ModelsController.php, scripts/Phalcon/Web/Tools/Controllers/ScaffoldController.php, tests/phpstan.php
Hello!
Added `phpstan` code analyzer. Level analyze - 1.
Thanks
=> Add phpstan analyzer

README.md, scripts/Phalcon/Devtools/Version.php
Hello!
* Link to issue: - 
Changed devtools version
Thanks
=> Update version number

.travis.yml, README.md, scripts/Phalcon/Builder/Controller.php, scripts/Phalcon/Builder/Project.php, scripts/Phalcon/Builder/Scaffold.php, scripts/Phalcon/Commands/Command.php, scripts/Phalcon/Db/Adapter/Pdo/PostgresqlExtended.php, scripts/Phalcon/Devtools/Version.php, scripts/Phalcon/Error/ErrorHandler.php, scripts/Phalcon/Initializable.php, scripts/Phalcon/Migrations.php, scripts/Phalcon/Mvc/Model/Migration.php, scripts/Phalcon/Version/IncrementalItem.php, scripts/Phalcon/Version/ItemCollection.php
Hello!
Improve phpstan analyse level
Thanks
=> improve phpstan analise level

scripts/Phalcon/Initializable.php
Hello!
* Link to issue: #1136
Fix initVolt method in initiazable. 
Thanks
=> Fix initVolt method in initiazable

README.md, scripts/Phalcon/Devtools/Version.php
Hello!
Update devtools version 
Thanks
=> Update devtools version

scripts/Phalcon/Mvc/Model/Migration.php
Hello!
* Link to issue: #1137
Fix additional slashed after migration in table.
Thanks
=> Fix additional slashes after migartion

phpstan.neon, scripts/Phalcon/Builder/AllModels.php, scripts/Phalcon/Builder/Scaffold.php, scripts/Phalcon/Commands/Builtin/Serve.php, scripts/Phalcon/Commands/Command.php, scripts/Phalcon/Commands/DotPhalconMissingException.php, scripts/Phalcon/Migrations.php, scripts/Phalcon/Mvc/Controller/Base.php, scripts/Phalcon/Mvc/Model/Migration.php, scripts/Phalcon/Mvc/Model/Migration/Profiler.php, scripts/Phalcon/Script/Color.php, scripts/Phalcon/Utils/FsUtils.php, scripts/Phalcon/Version/IncrementalItem.php, scripts/Phalcon/Version/ItemCollection.php
Hello!
Fixed phpstan tests
Thanks
=> Fixed PHPStan tests

scripts/Phalcon/Generator/Snippet.php, tests/_data/console/app/models/files/TestModel.php, tests/_data/console/app/models/files/TestModel2.php, tests/_data/console/app/models/files/TestModel3.php, tests/_data/console/app/models/files/Testmodel4.php
* Link to issue: #1169 
Fixed the #1169.
Thanks
=> add `column` parameter to `@Column` annotation property

scripts/Phalcon/Builder/AllModels.php, scripts/Phalcon/Builder/Component.php, scripts/Phalcon/Builder/Model.php, scripts/Phalcon/Commands/Builtin/AllModels.php, scripts/Phalcon/Commands/Builtin/Model.php, scripts/Phalcon/Exception/InvalidParameterException.php, scripts/Phalcon/Exception/RuntimeException.php, scripts/Phalcon/Exception/WriteFileException.php, scripts/Phalcon/FactoryOptions.php, scripts/Phalcon/Generator/Snippet.php, scripts/Phalcon/Options/OptionsAware.php, tests/console/GenerateSingleModelCept.php
Hello!
Add options container and implement it in model generating. Code refactor.
Thanks
=> Add option container and implements in model generator

scripts/Phalcon/Builder/Model.php, scripts/Phalcon/Generator/Snippet.php
Hello!
Improve code in model generator.
Thanks
=> Improve code in model generator

scripts/Phalcon/Db/Adapter/Pdo/PdoMysql.php, scripts/Phalcon/Db/Adapter/Pdo/PdoPostgresql.php, scripts/Phalcon/Db/Dialect/DialectMysql.php, scripts/Phalcon/Db/Dialect/DialectPostgresql.php, scripts/Phalcon/Mvc/Model/Migration.php, tests/unit/Db/Adapter/Pdo/PostgresqlTest.php
Hello!
* Link to issue: https://github.com/phalcon/incubator/issues/854
Change namespaces for Db. devtools and incubator have the same namespaces. 
Thanks
=> Change namespaces for DB section

CHANGELOG.MD, CONTRIBUTING.md, LICENSE.txt, README.md
Hello!
Add license, changelog, readme
Thanks
=> Add license and info files

.travis.yml, composer.json, phpcs.xml.dist
Hello!
**In raising this pull request, I confirm the following :**
Add codesniffer
Thanks
=> Add codesniffer

config/config.php
Hello!
Add configuration file
Thanks
=> Add config

src/Modules/Core/Module/AbstractModule.php, src/Modules/Core/Module/ModuleInterface.php
Hello!
Add base class to create modules
Thanks
=> Add base class to create modules

src/Modules/Core/Exceptions/InvalidArgumentException.php, src/Modules/Core/Options/OptionsRegistry.php, src/Modules/Core/Options/OptionsRegistryInterface.php
Hello!
Add options container
Thanks
=> Add options container

scripts/Phalcon/Builder/Model.php, scripts/Phalcon/Builder/Scaffold.php, scripts/Phalcon/Commands/Builtin/Scaffold.php, scripts/Phalcon/Commands/Command.php, tests/_data/console/app/mysql/config.php, tests/_data/schemas/mysql/dump.sql, tests/console/GenerateScaffoldCept.php
Hello!
* Link to issue: #1211
Fix scaffold. Problem with generate config. Add config option to scaffold
Thanks
=> Fix scaffold. Problem with generate config

.travis.yml, scripts/Phalcon/Migrations.php
Hello!
Add default value to creating log table to prevent SQL error
Thanks
=> Add default value to creating log table to prevent SQL error

.travis.yml, composer.json
Hello!
* Type: dependencies
To prevent dependencies conflict improve `travis.yml` and `composer,json`
Thanks
=> Improve travis and composer.json

.travis.yml
Hello!
* Type: dependencies
Update phalcon version to 3.3.2 in travis
Thanks
=> Update phalcon version in travis

.travis.yml, composer.json
Hello!
* Type: dependencies
To prevent dependencies conflict improve `travis.yml` and `composer,json`
Thanks
=> 3.2.x Improve travis and composer.json

README.md, scripts/Phalcon/Devtools/Version.php
=> Bump version 3.2.13

README.md, scripts/Phalcon/Devtools/Version.php
Hello!
Bump version (3.4.0)
Thanks
=> Bump version [ci skip]

templates/project/modules/bootstrap_web.php, templates/project/simple/index.php
Hello!
* Link to issue: https://github.com/phalcon/phalcon-devtools/issues/1256
Small description of change:]
removed CR LF and TAB stripping before output to browser
Thanks
=> fix issue #1256

scripts/Phalcon/Commands/Builtin/Serve.php, tests/unit/ServeTest.php
=> Fixing phalcon serve on newer PHP versions - issue #1233

resources/elements/sidebar-menu.php
Hello!
* Link to issue: #1288 
Thanks
=> #1288 - Update of sidebar links

templates/webtools.config.php
Hello!
* Link to issue: #1290 
=> #1290 - Added comment for PTOOLS_IP

composer.json
=> #1282 - PHP upgrade from 5 to 7.2

scripts/Phalcon/Builder/Scaffold.php
Hello!
* Link to issue: #1178
Thanks
=> #1178 - Disabled lowering during usage of getters and setters

scripts/Phalcon/Web/Tools/Views/models/generate.volt
Hello!
* Link to issue: #1306 
=> #1306 - Fixed typo in namespace label

scripts/Phalcon/Commands/Builtin/Serve.php, tests/unit/ServeTest.php
Reverts phalcon/phalcon-devtools#1275
=> Revert "Fixing phalcon serve on newer PHP versions - issue #1233"

phalcon.bat
Hello!
* Link to issue: #1238
Thanks
=> #1238 - Reverted removal of phalcon.bat

composer.json
Hello!
* Link to issue: #1282
Thanks
=> #1282 - Update composer.json dependencies

scripts/Phalcon/Devtools/Version.php
Hello!
- [x I have checked that another pull request for this purpose does not exist
Thanks
=> Set version to 3.4.5 in branch

phalcon.bat
We did an ajustment in phalcon.bat file to running on windows
environment
Hello!
Thanks
=> Windows configuration

scripts/Phalcon/Builder/Project/Cli.php, scripts/Phalcon/Builder/Project/Micro.php, scripts/Phalcon/Builder/Project/Modules.php, scripts/Phalcon/Builder/Project/Simple.php, tests/console/GenerateProjectCept.php
Hello!
* Link to issue: #1336
Thanks
=> #1336 - Project config.php file

scripts/Phalcon/Builder/Project/Cli.php, scripts/Phalcon/Builder/Project/Micro.php, scripts/Phalcon/Builder/Project/Modules.php, scripts/Phalcon/Builder/Project/Simple.php, tests/console/GenerateProjectCept.php
Hello!
* Link to issue: #1336
Thanks
=> #1336 - Project config.php file [v4]

scripts/Phalcon/Web/Tools/Controllers/ScaffoldController.php
Hello!
* Link to issue: #1320
Thanks
=> #1320 - Fix blank page on Scaffold form page

scripts/Phalcon/Web/Tools/Controllers/ScaffoldController.php
Hello!
* Link to issue: #1320
Thanks
=> #1320 - Fix blank page on Scaffold form page [v4]

src/Bootstrap.php, src/Providers/AccessManagerProvider.php, src/Providers/ConfigProvider.php, src/Providers/LoggerProvider.php, src/Providers/RouterProvider.php, src/Providers/VoltProvider.php
=> V4 Bug Fixes

src/Bootstrap.php, src/Builder/Component/Scaffold.php, src/Providers/AccessManagerProvider.php, src/Providers/ConfigProvider.php, src/Providers/LoggerProvider.php, src/Providers/RouterProvider.php, src/Providers/VoltProvider.php, src/Web/Tools/Controllers/ScaffoldController.php
Hello!
* Link to issue: #1320
Current branch must be merged after - https://github.com/phalcon/phalcon-devtools/pull/1359
Thanks
=> #1320 - Fix Scaffold white screen

scripts/Phalcon/Web/Tools/Controllers/ScaffoldController.php
Hello!
* Link to issue: #1320
Thanks
=> #1320 - Fix Scaffold white screen [v3.4]

.ci/build-phar.sh, .ci/install-box.sh, .travis.yml, bootstrap/autoload.php, box.json, composer.json
Hello!
* Link to issue: #1248 
Thanks
=> #1248 - Box 3 upgrade

README.md
=> Add Discord Shield into README.md

.codecov.yml, .travis.yml, README.md, codeception.yml
Hello!
* Type: new feature | code quality
* Link to issue: #1365
Thanks
=> #1365 - Integrate Codecov

box.json
Hello!
* Link to issue: #1368
Thanks
=> #1368 - Add phalcon.phar comporession

.travis.yml
Hello!
* Link to issue: #1363
@niden, @sergeyklay After merge, remove `GH_TOKEN` env variable from secrets in repository settings.
Thanks
=> #1363 - Unify GitHub token

.travis.yml, bootstrap/autoload.php, composer.json, src/Version.php
Hello!
* Type: bug fix | code quality
* Link to issue: #1370
Thanks
=> #1370 - Update Phalcon version to 4.0.0-RC.3

scripts/Phalcon/Mvc/Model/Migration.php
Hello!
* Link to issue: https://github.com/phalcon/migrations/issues/22
Thanks
=> Add column types without size

templates/project/modules/services.php
Hello!
* Link to issue: #1395
Thanks
=> #1395 - Change Deprecated volt options

templates/scaffold/no-forms/Controller.php, templates/scaffold/no-forms/views/edit.phtml, templates/scaffold/no-forms/views/edit.volt, templates/scaffold/no-forms/views/index.phtml, templates/scaffold/no-forms/views/index.volt, templates/scaffold/no-forms/views/new.phtml, templates/scaffold/no-forms/views/new.volt, templates/scaffold/no-forms/views/search.phtml
Hello!
* Type: bug fix | code quality
* Link to issue: #1402
Thanks
=> #1402 - Remove requirements of SessionBag

src/Builder/Component/Scaffold.php, tests/console/GenerateScaffoldCept.php
Hello!
* Link to issue: #1400
Thanks
=> #1400 - Fix empty namespace for controllers and models

scripts/Phalcon/Mvc/Model/Migration.php
Hello!
* Link to issue: #1399
Thanks
=> #1399 - Exclude size for TYPE_DOUBLE

templates/project/simple/index.php
Hello!
* Link to issue: #1417
Thanks
=> #1417 - Swap include order of services.php and router.php

scripts/Phalcon/Migrations.php
Hello!
* Link to issue: https://github.com/phalcon/phalcon-devtools/issues/1438
Migrations script now can handle the migrations directory well.
Thanks
=> Fix Bug #1438

CHANGELOG.md, box.json
Hello!
Composer dependencies are not discovered if directories or files are specified.
Resolution found here: humbug/box#457
=> Fix .phar build

README.md
Update README.md with phalcon-devtools v4.0.3 content
=> #1458 - Update README.md

composer.json
Remove problematic package vlucas/phpdotenv from composer.json
=> #1460 - Remove vlucas/phpdotenv package from composer.json

CHANGELOG.md, src/Generator/Snippet.php, tests/_data/console/app/models/files/TestModel.php, tests/_data/console/app/models/files/TestModel2.php, tests/_data/console/app/models/files/TestModel3.php, tests/_data/console/app/models/files/TestModel5.php, tests/_data/console/app/models/files/Testmodel4.php
Hello!
* Link to issue: #1478 
Fixed models generated findFirst() return type
Thanks
=> ISSUE-1478: Fixed models generated findFirst() return type

CHANGELOG.md, src/Builder/Component/Model.php, src/Builder/Component/Scaffold.php, src/Generator/Snippet.php, tests/_data/console/app/models/files/TestModel.php, tests/_data/console/app/models/files/TestModel2.php, tests/_data/console/app/models/files/TestModel3.php, tests/_data/console/app/models/files/TestModel5.php, tests/_data/console/app/models/files/Testmodel4.php
Hello!
* Link to issue: #1468 
Fixed wrong request filtering on controller creation via `request->getPost()`
Thanks
=> ISSUE-1468: Fixed wrong request filtering

CHANGELOG.md, src/Builder/Component/Controller.php, src/Builder/Component/Model.php, src/Builder/Component/Scaffold.php, src/Generator/Snippet.php, tests/_data/console/app/models/files/TestModel.php, tests/_data/console/app/models/files/TestModel2.php, tests/_data/console/app/models/files/TestModel3.php, tests/_data/console/app/models/files/TestModel5.php, tests/_data/console/app/models/files/Testmodel4.php
Hello!
* Link to issue: #1467 
Fixed empty namespace generating such as `namespace ;`
Thanks
=> ISSUE-1467: Fixed empty namespace generating

CHANGELOG.md, src/Bootstrap.php
Hello!
* Link to issue: #1500 
Fixed not found error when webtools located at subfolder
Thanks
=> ISSUE-1500: Fix not found error on webtools
