scripts/Phalcon/Web/Tools.php

When using config.ini (option --use-config-ini) the paths are set to one extra level up.

Fix broken paths when using config.ini

---

scripts/Phalcon/Version/Item.php

When the fromVersion equals to finalVersion (eg: 1.0.0 == 1.0.0), the migration run for 1.0.0 every time `phalcon migration run` invoked

Fix duplicate migration if initalVersion == finalVersion

---

scripts/Phalcon/Builder/Component.php

This PR fixed wrong config detect behaviour:
```php
// For example
$path = '.';
protected function _getConfig($path)
{
// ...
foreach (array('app/config/', 'config/') as $configPath) {
if (file_exists($path . $configPath . "/config.ini")) {
// ./app/config//config.ini
// ./config//config.ini
}
}
// ...
}
```

Improved config detection

---

scripts/Phalcon/Builder/Scaffold.php

Out of all the `Column::TYPE_*` methods, there is no `ENUM`. Doing some debugging, it looks like enum is represented as **5**. This PR adds support for adding a `staticSelect` field when an enum field is detected.
Here are the results for the PHP template. The field is served an empty array, not sure if there is a way to grab the field enum values, but that would be awesome.
```php
<?php echo $this->tag->selectStatic(array("column_name", array())) ?>
```

add support for enum in scaffolding

---

ide/2.0.0/Phalcon/di/Injectable.php

In version 2.0 intellisense for magic methods stop working. That's because of the missing variables in devtools. This fixes the problem
http://forum.phalconphp.com/discussion/6520/phalcon-2-in-phpstorm

fix intellisense on magic methods

---

scripts/Phalcon/Builder/Scaffold.php

For some reason the TEXT column was being assigned to a `type="date"` in the [Scaffold component](https://github.com/phalcon/phalcon-devtools/blob/221045950e70ed9674e3f6de9e10c630c858a693/scripts/Phalcon/Builder/Scaffold.php#L402). This change turns any TEXT column into a textarea field.
Results: 
```php
<?php echo $this->tag->textArea(array("column_name", "cols" => 30, "rows" => 4)) ?>
```

improve scaffold with textarea on TEXT columns. Remove date type for TEXT

---

scripts/Phalcon/Builder/Model.php

I was getting the error:
, but this just happened on these last commits, I tried to understand the code, and came to the conclusion that on line 248 the condition becomes false, indeed, because `$this->_options['modelsDir']` is actually set but the path doesn't really exist.
The right path is set on line 254:
$modelsDir = $config->application->modelsDir;
Then the result is,
Windows guys,...sorry.. I don't care...
---
Hope, it helps someone..I was getting in panic...

better condition in scripts/Phalcon/Builder/Model.php

---

scripts/Phalcon/Builder/Controller.php

This fixes issues where the constant is transformed into a string and used in concatenation :(

Properly spell DIRECTORY_SEPARATOR

---

scripts/Phalcon/Builder/Project.php
scripts/Phalcon/Commands/Command.php

Now project generator can create path recursive (project type + project name).
For example:
```sh
$ phalcon project --name MyShop --directory=simle --trace --enable-webtools --use-config-ini >/dev/null 2>&1
$ phalcon project --name MyBlog --directory=simle --trace --enable-webtools --use-config-ini >/dev/null 2>&1
$ ls -l simle/
total 8
drwxrwxr-x 5 klay klay 4096 May  2 14:44 MyBlog
drwxrwxr-x 5 klay klay 4096 May  2 14:44 MyShop
```

Fix project generator

---

scripts/Phalcon/Web/Bootstrap.php
scripts/Phalcon/Web/CodeMirror.php
scripts/Phalcon/Web/InstallerInterface.php
scripts/Phalcon/Web/Tools.php

Now each resource installer must implement InstallerInterface.
Removed static methods for testing purposes.
Part of #321

Refactored resource installers

---

templates/project/micro/services.php

**DbAdapter** expected as param something like this
```
array(
'adapter'    => 'Mysql',
'host'       => 'localhost',
'username'   => 'root',
'password'   => 'root',
'dbname'     => 'my_db_name',
'charset'    => 'utf8',
);
```
without **database->** part, it is passing the entire config array and when we try to execute a phql statement/query, it throws a php notice like this:
```
Notice: Array to string conversion in config/services.php on line 32
```

fix DbAdapter param according to expected value

---

scripts/Phalcon/Builder/Model.php

When generating models, related Model names are not always camelized. This fixes that issue.

FIxed camelize issue with alias and reference table names

---

scripts/Phalcon/Builder/Model.php

Currently, --excludefields works only with --get-set option.
This PR fixes --excludefields behavior and enables to exclude fields without --get-set option.
This is re-submit of https://github.com/phalcon/phalcon-devtools/pull/432.

Fix phalcon model --excludefields option

---

scripts/Phalcon/Web/Tools.php

A small change that allows operation even in older versions, instantiating the class before calling the method of the same.
**Resend on branch

Adapt the php-dev-tools to work with oldest version of PHP < 5.4

---

.gitignore
README.md
box.json
composer.json

Brings the ability of the package as a PHP archive file (phar).
- Declare obsolete scripts `phalcon.bat`, `phalcon.sh`.
```bash
$ box build -v
* Building...
? Output path: .../phalcon-devtools/phalcon.phar
? Setting replacement values...
+ @git_tag@: v2.0.1-76-gfcf2253
? Adding Finder files...
+ .../phalcon-devtools/scripts/...
? Adding files...
+ .../phalcon-devtools/webtools.php
? Adding main file: .../phalcon-devtools/phalcon.php
? Generating new stub...
* Done.
$ chmod +xr ./phalcon.phar
$ mv -v phalcon{.phar,}
phalcon.phar -> phalcon
$ file ./phalcon
./phalcon: a php script text executable
$ ./phalcon
Phalcon DevTools (2.0.1)
Available commands:
commands (alias of: list, enumerate)
controller (alias of: create-controller)
model (alias of: create-model)
all-models (alias of: …
```

Added support for build phalcon.phar

---

composer.json

cannot find the box from packagist.org; the correct is "kherge/box", but not just "box".

fixed composer error

---

scripts/Phalcon/Web/Tools/controllers/ControllerBase.php

the correct path is the path of file "webtools.php",  not the path of the project root.   when i create project with devtools and enable webtools,  the "webtools.php" file is in the public dir.

fixed the path error of webtools page

---

templates/project/modules/routes.php

The routes set here are not actually being set, it just coincidentally works with a single demo module due to the "defaultNamespace" set in services.php

Send router back to DI

---

phalcon.pear
phalcon.php

`phalcon command` outputs STDOUT(standard output) even if it throws the exception.
So below doesn't work correctly.
```sh
$ phalcon invalid-command 2> stderr.log
```
outputs STDERR(standard error) when an error happened.

Add standard error output

---

scripts/Phalcon/Web/Tools/controllers/ScaffoldController.php

When I launch webtools, I found this error message.
I fixed it.
```
Warning: sprintf(): Too few arguments in scripts/Phalcon/Web/Tools/controllers/ScaffoldController.php on line 35
```

Remove unnecessary comment

---

phalcon.php

In order to execute the following command can be repeated
phalcon model --namespace=Service\\ORM --extends=Service\\ORM\\BaseModel --get-set --force --name=tablename
user custom BaseModel class  needs to be loaded

add user custom autoload

---

scripts/Phalcon/Migrations.php
scripts/Phalcon/Utils.php

I know PDO SQLite migrations are not fully working (due to ALTER table limitations), but the following three commits should at least improve support for running migrations (I successfully converted structure from MySQL to SQLite).
* 2866803 fixes the issue described in PR #638.
* 3f543dc changes MySQL's `NOW()` in PHP's `date()`. The latter is already used in `Migrations.php`.
* 7e2c1cd fixes the issue where the file path is added as schema (see below).
Example of issue the last commit fixes (note the file name is used as schema in the CREATE TABLE statement):
```
1459346099.167: CREATE TABLE "/opt/backend/app/../data/df.db"."projects" (  `ID` INTEGER NOT NULL,  `name` VARCHAR(128) NOT NULL,  `userID` INTEGER NOT NULL,  `defaultQuestionID` INTEGER,  `access` VARCHAR(512),  `metadata` TEXT …
```

Improve support for PDO Sqlite migrations

---

ide/2.0.9/Phalcon/mvc/view/engine/Volt.php

Extending Volt class and overriding callMacro($name, $arguments) renders errors due to signature mismatch:
ErrorException: Declaration of Pow\Mvc\Volt::callMacro() should be compatible with Phalcon\Mvc\View\Engine\Volt::callMacro($name, array $arguments)
Method signature should probably typehint $arguments as array

Volt, overriding callMacro renders error

---

ide/stubs/Phalcon/mvc/Model.php

I think, that we can fix it in other version of documentation too (I've tested this case only in Phalcon 2.0.8). As I see, changing `ide/stubs` directory will change other cases too, am I right?

added boolean as return type of findFirst() method

---

templates/webtools.config.php

Added APP_PATH constant to webtools config file in order to fix generation via webtools
Without this change, webtools could not detect correct model and controller folders.
In order to reproduce and test:
1. Create a new project WITHOUT ini config:
`phalcon-2.0.x project phalconphp --enable-webtools`
2. Open Controllers tab in webtools
```
Sorry, WebTools doesn't know where the controllers directory is.
Please add the valid path for controllersDir in the application section.
```
Notice: This is also relevant for branch `2.1.x`. However in `2.1.x` there is some other issue related to "scaffold" creation. 
Signed-off-by: Sebastian Baum <sebastian.baum@ion2s.com>

webtools 2.0.x folders patch

---

scripts/Phalcon/Builder/Model.php

`php vendor/phalcon/devtools/phalcon.php model posts` caused the following error:
```
PHP Warning:  file_put_contents(/var/www/default/../app/models/Posts.php): failed to open stream: No such file or directory in /var/www/default/vendor/phalcon/devtools/scripts/Phalcon/Builder/Model.php on line 526
PHP Stack trace:
PHP   1. {main}() /var/www/default/vendor/phalcon/devtools/phalcon.php:0
PHP   2. Phalcon\Script->run() /var/www/default/vendor/phalcon/devtools/phalcon.php:86
PHP   3. Phalcon\Script->dispatch() /var/www/default/vendor/phalcon/devtools/scripts/Phalcon/Script.php:150
PHP   4. Phalcon\Commands\Builtin\Model->run() /var/www/default/vendor/phalcon/devtools/scripts/Phalcon/Script.php:125
PHP   5. Phalcon\Builder\Model->build() …
```

Adjusting modelsDir if used from outside of project dir

---

ide/stubs/Phalcon/mvc/Model.php

there is broken return type as no imports provided and there is no interface in same namespace

[2.0.10] fix PHPDoc into \Phalcon\Mvc\Model.php

---

templates/project/modules/Module_web.php
templates/project/modules/services.php
templates/project/simple/services.php

This is merely a convention change that I hope will ease some of the difficulties that people have had with the Volt service not working correctly when normal and simple views are combined.

Set Volt service to shared and change its name from 'voltService' to 'voltShared'

---

scripts/Phalcon/Version/ItemCollection.php

Was error:
```
PHP Fatal error:  Out of memory (allocated 1145053184) (tried to allocate 2147483656 bytes) in /vagrant/vendor/phalcon/devtools/scripts/Phalcon/Version/IncrementalItem.php on line 62
PHP Stack trace:
PHP   1. {main}() /vagrant/vendor/phalcon/devtools/phalcon.php:0
PHP   2. Phalcon\Script->run() /vagrant/vendor/phalcon/devtools/phalcon.php:97
PHP   3. Phalcon\Script->dispatch() /vagrant/vendor/phalcon/devtools/scripts/Phalcon/Script.php:150
PHP   4. Phalcon\Commands\Builtin\Migration->run() /vagrant/vendor/phalcon/devtools/scripts/Phalcon/Script.php:125
PHP   5. Phalcon\Migrations::run() /vagrant/vendor/phalcon/devtools/scripts/Phalcon/Commands/Builtin/Migration.php:141
PHP   6. Phalcon\Mvc\Model\Migration::scanForVersions() …
```

Bug migrations

---

scripts/Phalcon/Version/ItemCollection.php

fix #750 - this fixes the problem when migration is timestampbased - default value is not according to REGEX requirement

fix initial migration timestamp based

---

templates/project/cli/services.php
templates/project/micro/services.php
templates/project/modules/services.php
templates/project/simple/services.php

charset is not a parameter for PostgreSQL Connections and thus switching to PostgreSQL inside an automatically generated project throws exceptions whenever something a database connection is attempted.
this proposed change keeps it more flexible by unsetting the key 'charset' from the adapters config array if the adapter is PostgreSQL

Fixed possible problems with PostgreSQL-Connections in generated code

---

scripts/Phalcon/Builder/Project/Modules.php

I was going through my commit history and I noticed that I was using Eduar's email from a copy-paste error.  So then I went to fix that and then I noticed that my entry had been removed.  So now I am adding it back with the correct email.

Adding attribution

---

scripts/Phalcon/Builder/Model.php

I use postgres. My db name is "test" and my schema name is "test".
If I build the models, with the script, it creates them correctly, but I receive this error when I try to use a table: "Table 'table' doesn't exist in database when dumping meta-data for Table".
After trying to figure out where the problem was, I realized that into the initialization method of the model, the method "setSchema" was not called. 
Why when I set the schema (phalcon model --schema=test ...) with dev-tools, this checks if the schema name is the same as the database name ($schema != $config->database->dbname)?

Problem if u have db name == schema name on Postgres

---

templates/project/simple/config.php

The issue is that dev tools templates only understand being in the root directory of a web space or vhost and this is never the case in my projects.  One downside of this pull request is that now the ini config doesn't match the normal one but I don't see how this can be done with an ini file.  Its still no worse for ini then it was so it will just be a different flavor.
* This should handle Windows and Unix path separators.
* This only changes the `simple` template and later I will add the `modules` fix as well (but I'm having much more serious issues with `modules` at the moment).

Allow 'simple' project template 'url' service to understand non-root project paths.

---

scripts/Phalcon/Mvc/Model/Migration.php

Fixed error 897 - from fork https://github.com/Arrim/phalcon-devtools/commit/353d07dee84a1835b38d8697cb0a5c4387a429c2
Added array_unique to avoid duplicate columns

#897 - fixed duplicate columns in Migration

---

templates/project/modules/config.php
templates/project/modules/routes.php
templates/project/modules/services_web.php

I added the 'url' fix fom 'simple' project.
Another issue was was due to some of the `modules` code being copied from `simple` where `Module` was being replaced with `Controllers`.  I changed it to match to the end of the string because the module classes have two "Module" strings in them, once for "Modules" and then another time at the end for the class name itself.
I tested a dispatcher forward as well as the following paths and they all work:
* /projects_container/test_modules/
* /projects_container/test_modules/index
* /projects_container/test_modules/index/index
* /projects_container/test_modules/frontend
* /projects_container/test_modules/frontend/index
* /projects_container/test_modules/frontend/index/index
* /projects_container/test_modules/frontend/test
* …

Fixes and cleanups for 'modules' project

---

phalcon.sh
scripts/Phalcon/Mvc/Model/Migration.php
scripts/Phalcon/Version/VersionAwareTrait.php

This is just a suggestion, but I ran into some very annoying issues trying to import a large dataset with newlines inside text and memo fields. There are also some typo fixes (one in a comment and another in Phalcon\Version\VersionAwareTrait that was breaking migrations)

Use csv for data export

---

scripts/Phalcon/Migrations.php

This should be able to handle multiple tables listed with the `--table` option to address Issue https://github.com/phalcon/phalcon-devtools/issues/775

Enable multiple, comma delimited table names for --table option

---

bootstrap/autoload.php

Realted to #778
Type: bug fix
- Seek for custom autoloader change, from PTOOLSPATH to cwd.
- Typo fix
Thanks

Seek for custom autoloader relatively from dir. where DevTools was invoked

---

scripts/Phalcon/Mvc/Model/Migration.php

Hello!
* Link to issue: https://github.com/phalcon/phalcon-devtools/issues/238
This bug occurs when the development db name is different from the production db name. When the migration tool generates the migration script from the development environment, the references contains the development db name (referencedSchema). When doing the migration in production server, the migration tool still reads referencedSchema even the db config is set to production because the db name in referencedSchema is hardcoded within the script. By removing referencedSchema from generating the migration script …

fix db referencing problem

---

ide/stubs/Phalcon/mvc/Model.php

ResultsetInterface was returned, but namespace was not specified. It was trying to load "\Phalcon\Mvc\ResultsetInterface" and not "\Phalcon\Mvc\Model\ResultsetInterface"
I'll update it in the official Phalcon repository so it can be generated correctly next time.
Hello!
Thanks

IDE Stubs - Update Phalcon\Mvc\Model -> getRelated function @return type

---

ide/1.3.0/Phalcon/Mvc/Model/Query.php

The old is **Ṕhalcon\Mvc\ModelInterface** changed into **\Phalcon\Mvc\ModelInterface**
Hello!
Thanks

Update the return of getSingleResult

---

scripts/Phalcon/Migrations.php

This change will make possible for classes that extend Migrations to be able to with $_storage variable
this is useful in my case for modular setup each one with it's own migration and path with version.
Hello!
Thanks

Code Quality Migration::$_storage to protected

---

ide/stubs/Phalcon/db/Adapter.php

Change return type for getSqlVariables to array (from string).
Hello!
- [*] Code Quality
- [*] I have read and understood the [Contributing Guidelines][:contrib:]?
- [*] I have checked that another pull request for this purpose does not exist.
Return type was not correct. I've changed it to array for getSqlVariables
Thanks

Update getSqlVariables return type

---

README.md
scripts/Phalcon/Commands/Command.php

Hello!
* Link to issue: https://github.com/phalcon/phalcon-devtools/issues/980
Small description of change: This is adding way to load options for commands from `phalcon.json`(or any other extension) file in root project category.
Thanks

Added parameters loading from additional devtools config file

---

scripts/Phalcon/Web/Tools/Controllers/MigrationsController.php

Hello!
According to devtools/scripts/Phalcon/Migrations.php 276 line, Should be "@", not "all". And this fixed migration "run" from webtools, before that they did not do anything. (at least for me)
Correct me please if I'm wrong
Thanks

fix migration for all tables in webtools

---

bootstrap/autoload.php

Hello!
* Link to issue: #1035
remove symbols `'` or `"` when conts `PTOOLSPATH` is determined from system
Thanks

Remove symbols when const `PTOOLSPATH` is determined from system in autoload.php

---

scripts/Phalcon/Mvc/Controller/Base.php

Hello!
* Type: suggest 
I found webtools.php slowed down by remote request js_ie related js files, and it also requires openssl opened, or the page will be blank.
I think it is not necessary to combine and compress the few used js files which are remote files.
Thanks

directly link js_ie files to avoid slowing down the request

---

.travis.yml
README.md
codeception.yml
composer.json
phalcon.php
scripts/Phalcon/Commands/Builtin/Serve.php
tests/_output/.gitignore
tests/_support/Helper/Unit.php
tests/_support/UnitTester.php
tests/_support/_generated/.gitignore
tests/unit.suite.yml
tests/unit/ServeTest.php

Hello!
* Type: __new feature__ | __code quality__
* Link to issue: __No Issue__
In preparation for my meetup on July 20th I want to simplify the number of commands required to get a new project up and running. From Devtools a user can create an empty project and then immediately launch a development server to build up a hello world application.
In general this is inspired by the `rails server` command I use with RoR. This server is not expected to take the place of nGINx or Apache but when onboarding new users who man not have ever installed a webserver or are running windows. Using the builtin PHP webserver will keep users more focused on Phalcon and less on dependencies.
This is really a simple …

Add Serve Builtin Command to Devtools

---

scripts/Phalcon/Commands/Builtin/Serve.php
tests/unit/ServeTest.php

Hello!
* Type: **bug fix**
* Link to issue: #1041 | https://github.com/phalcon/docs/pull/1135
After reviewing https://github.com/phalcon/docs/blob/3.2/en/webserver-setup.md I realized I missed the required document root from the built-in php server command along with a need for the default entrypoint for devtools to be the `.htrouter.php` so this command can work out of the box as `phalcon serve` without the need for any additional arguments.
I have updated the tests and cleared a typo in the commands output. No additional behavior was changed just the addition of a new argument and improved documentation.
Thanks
[:contrib:]: …

Added document root default to serve command

---

phalcon.php
scripts/Phalcon/Commands/CommandsListener.php
scripts/Phalcon/Commands/DotPhalconMissingException.php
scripts/Phalcon/Commands/iSelfHealingException.php

Hello!
* Type: **new feature**
* Link to issue: #1054
When the exception for a missing .phalcon folder is raised the user is prompted and the missing folder is created automatically. Once the folder is created the command is re-executed.
I have added an interface for "Self-Healing Exceptions" so this can be propagated to other locations where cli execution stops but could be resolved.
Thanks

Make phalcon self-healing when executing an external false command when .phalcon folder is missing

---

scripts/Phalcon/Builder/AllModels.php
scripts/Phalcon/Commands/Builtin/AllModels.php

Hello!
* Link to issue: #913
added `camelize` option for `all-models` command. It works like creating model for one table that using this option
Thanks

Added camelize option for all-model command

---

scripts/Phalcon/Builder/Model.php

Hello!
Duplicate call initialization setSource method when generating a model. This method initialize before.
Thanks

deleted duplicate code

---

scripts/Phalcon/Commands/Builtin/AllModels.php

Hello!
* Link to issue: #234
models created with commands `all-models` and `model` are same. Option `validations` in `all-models` command is unused.
Thanks

deleted unused param when gereneration all-model

---

scripts/Phalcon/Builder/Scaffold.php
templates/scaffold/no-forms/Controller.php

Hello!
* Link to issue: #203 
Fixed problem in controller when using command `phalcon scaffold --get-set --table-name=foo-bar`. Generated controller contains without `get` methods.
Thanks

Bug fix controller when use getters and setters

---

scripts/Phalcon/Db/Dialect/PostgresqlExtended.php
scripts/Phalcon/Mvc/Model/Migration.php
tests/_support/Helper/Db/Dialect/PostgresqlTrait.php

Hello!
* Link to issue: #238
Fixed `referencedSchema` and added it when migration generating
Thanks

Fixed referencedSchema in migration for Postgresql

---

scripts/Phalcon/Builder/Scaffold.php

Hello!
* Link to issue: #1067
Fixed problem in controller and view with hyphen in tables name when generating scaffold.
Thanks

Fixed problem with hyphen in table names

---

scripts/Phalcon/Commands/Builtin/Model.php
scripts/Phalcon/Utils.php
tests/unit/UtilsTest.php

Hello!
* Link to issue: #1056
Fixed problem with class name when generating model
Thanks

Fixed problem with class name when generating model

---

scripts/Phalcon/Builder/Model.php
scripts/Phalcon/Utils.php
tests/unit/UtilsTest.php

Hello!
* Link to issue: #1070
Fixed name fields in models after generating
Thanks

Fixed name fields in Model when generationg model

---

scripts/Phalcon/Builder/Model.php

Hello!
Generation of getters/setters was not working correctly due to the camelize parameters being concatenated instead of two separate parameters.
Thanks

* Fix getters/setters camelize concat issue

---

scripts/Phalcon/Commands/Builtin/AllModels.php

Hello!
**In raising this pull request, I confirm the following :**
Option `models` for command `all-models` isn't obviously and should be like for option for `model`.
Thanks

Changed title of option  all-models for folder where models are located

---

scripts/Phalcon/Builder/Scaffold.php

Hello!
* Link to issue: #1078
Fixed generated controller and view for the scaffold. When generating scaffold, controller and search view contain variable with first big character.
Thanks

Fixed generated controller and view for the scaffold

---

scripts/Phalcon/Migrations.php

Hello!
This fixes defining the 'end_time' column properly when creating the table to track migration versions.
Thanks

* Fix creating table to track migration versions in the db

---

scripts/Phalcon/Builder/Model.php

Hello!
When model is generating with set namespace `phalcon model testing_child --namespace="FOO\Bar" --extends="foobar"`. Model has namespace `FOO\Bar\\TestingParent` in `belongsTo()`
Thanks

Fixed generated namespace when model generating with namespace

---

scripts/Phalcon/Builder/Project/Micro.php
scripts/Phalcon/Builder/Project/Modules.php
scripts/Phalcon/Builder/Project/Simple.php
scripts/Phalcon/Commands/Builtin/Project.php
scripts/Phalcon/Commands/Builtin/Scaffold.php
templates/project/micro/views/404.volt
templates/project/micro/views/index.volt

Hello!
* Link to issue: #66
Added option `--template-engine=s` for creating project. It makes possible to choose view engine `volt` or `phtml`
Thanks

Added option template-engine for project command

---

scripts/Phalcon/Migrations.php

Hello!
* Link to issue: #1002
Changed query for deleting row from migration log table, because for PostgreSQL `LIMIT` doesn't work.
Thanks

Fixed query for deleting row from migration log table

---

scripts/Phalcon/Builder/AllModels.php
scripts/Phalcon/Builder/Model.php
scripts/Phalcon/Commands/Builtin/Model.php

Hello!
* Type: bug fix & new feature
* Link to issue: #680
Added option `config=s` to `model` command and fixed similar option for `all-models`
Thanks

Fixed config path in allmodel and added to model

---

.travis.yml
scripts/Phalcon/Mvc/Model/Migration.php
scripts/Phalcon/Utils/Nullify.php
tests/_bootstrap.php
tests/_data/console/app/postgresql/config.php
tests/_data/console/app/test_insert_delete/migrations/1.0.0/test_insert_delete.php
tests/_data/console/app/test_insert_delete/migrations/1.0.1/test_insert_delete.dat
tests/_data/console/app/test_insert_delete/migrations/1.0.1/test_insert_delete.php
tests/_data/console/app/test_insert_delete/migrations/1.0.2/test_insert_delete.dat
tests/_data/console/app/test_insert_delete/migrations/1.0.2/test_insert_delete.php
tests/_data/schemas/postgresql/dump.sql
tests/_support/Helper/Utils/NullifyTrait.php
tests/_support/helpers.php
tests/console.suite.yml
tests/console/GenerateMysqlMigrationCept.php
tests/console/GeneratePostgresqlMigrationCept.php
tests/console/RunMysqlMigrationCept.php
tests/console/RunPostgresqlMigrationCept.php
tests/unit/Utils/NullifyTest.php

Hello!
* Link to issue: #988
Array with data for inserting has all values as string. Added checking `null` values in array for  `batchInsert()`.
Thanks

Changed batchInsert method inserting data to table for migration

---

scripts/Phalcon/Migrations.php
tests/_data/console/app/test_many_running/migrations/1.0.0/test_many_running.php
tests/_data/console/app/test_many_running/migrations/1.0.1/test_many_running.php
tests/_data/console/app/test_many_running/migrations/1.0.10/test_many_running.php
tests/_data/console/app/test_many_running/migrations/1.0.11/test_many_running.php
tests/_data/console/app/test_many_running/migrations/1.0.12/test_many_running.php
tests/_data/console/app/test_many_running/migrations/1.0.2/test_many_running.php
tests/_data/console/app/test_many_running/migrations/1.0.3/test_many_running.php
tests/_data/console/app/test_many_running/migrations/1.0.4/test_many_running.php
tests/_data/console/app/test_many_running/migrations/1.0.5/test_many_running.php
tests/_data/console/app/test_many_running/migrations/1.0.6/test_many_running.php
tests/_data/console/app/test_many_running/migrations/1.0.7/test_many_running.php
tests/_data/console/app/test_many_running/migrations/1.0.8/test_many_running.php
tests/_data/console/app/test_many_running/migrations/1.0.9/test_many_running.php
tests/_data/schemas/mysql/dump.sql
tests/console/RunMigrationCept.php

Hello!
* Link to issue: #1100
Getting current migration version from `.phalcon/migration-version` did without sorting
Thanks

Changed checking last version migration

---

scripts/Phalcon/Commands/Builtin/Migration.php
scripts/Phalcon/Commands/Command.php
scripts/Phalcon/Listeners/DbProfilerListener.php
scripts/Phalcon/Migrations.php
scripts/Phalcon/Mvc/Model/Migration.php
tests/_data/schemas/mysql/dump.sql
tests/console/GenerateDryVerboseMigrationCept.php
tests/console/RunDryVerboseMigrationCept.php

Hello!
* Link to issue: #215
Added option `--dry` and `--verbose` option for `migration` command. 
Thanks

Added option --dry --verbose to migration command

---

scripts/Phalcon/Builder/Scaffold.php

Hello!
* Link to issue: #1114
Fixed first character in public vars in controller when it was created by scaffold.
`$fooBar->SomeCol = $this->request->getPost("some-col");` - before.
`$fooBar->someCol = $this->request->getPost("some-col");` - after.
It was created in `createAction()` method.
Thanks

Fixed capitals first character in properties

---

scripts/Phalcon/Commands/Builtin/Migration.php
scripts/Phalcon/Console/OptionStack.php
scripts/Phalcon/Migrations.php
scripts/Phalcon/Mvc/Model/Migration.php
scripts/Phalcon/Mvc/Model/Migration/TableAware/ListTablesDb.php
scripts/Phalcon/Mvc/Model/Migration/TableAware/ListTablesInterface.php
scripts/Phalcon/Mvc/Model/Migration/TableAware/ListTablesIterator.php
tests/_data/console/app/test_table_prefix/migrations/1.0.0/issue595_1.php
tests/_data/console/app/test_table_prefix/migrations/1.0.0/issue595_2.php
tests/_data/schemas/mysql/dump.sql
tests/console/GenerateTablePrefixMigrationCept.php
tests/console/RunTablePrefixMigrationCept.php
tests/unit/Console/OptionStackTest.php
tests/unit/Mvc/Model/Migration/TableAware/ListTablesDbTest.php
tests/unit/Mvc/Model/Migration/TableAware/ListTablesIteratorTest.php

Hello!
* Link to issue: #595
Added table prefix to generate/run migration.
Thanks

Added table prefix to generate/run migration

---

scripts/Phalcon/Initializable.php

Hello!
* Link to issue: #1130
Fix cache directory path for initialization volt cache directory
Thanks

Fixed volt template engin cache dir

---

scripts/Phalcon/Initializable.php

Hello!
Fixed `initUi()` method.
Thanks

Fixed initUi

---

scripts/Phalcon/Builder/Model.php
tests/_data/console/app/models/files/TestModel.php
tests/_data/console/app/models/files/TestModel2.php
tests/_data/console/app/models/files/TestModel3.php
tests/_data/console/app/models/files/Testmodel4.php
tests/_data/schemas/mysql/dump.sql
tests/console/GenerateMultyModelsCept.php
tests/console/GenerateSingleModelCept.php

Hello!
* Link to issue: #1143, #1135
Fix different file name with command `all-models` and `model`
Thanks

Fix different model file name

---

scripts/Phalcon/Web/Tools.php

Hello!
* Link to issue: #1147
Fix path where `.css` file will be put. 
Thanks

Fix devtools css path

---

scripts/Phalcon/Builder/Scaffold.php

Hello!
The correct call to file_exists() should be with $viewPath as parameter AFAIK. The call should be file_exists($viewPath). This could be a potential bug.
Thanks

Corrected the Parentheses in 'if' on line 598

---

scripts/Phalcon/Builder/Model.php
scripts/Phalcon/Generator/Snippet.php

Hello!
Model generates method's wrong field description. I've field `ProducType`.
`Method to set the value of field producType` instead `Method to set the value of field `ProducType`
Thanks

Fix field name in model method doc

---

scripts/Phalcon/Builder/AllModels.php
scripts/Phalcon/Commands/Builtin/AllModels.php
tests/console/GenerateMultyModelsCept.php

Hello!
Add option `annotate` to `all-model` command
Thanks

Add option annotation to all-model command

---

scripts/Phalcon/Commands/DotPhalconMissingException.php

Hello!
Delete definition string type in method 
Thanks

Delete define string type in method

---

templates/project/micro/views/404.phtml
templates/project/micro/views/404.volt
templates/project/micro/views/index.phtml
templates/project/micro/views/index.volt
templates/project/modules/views/index.phtml
templates/project/modules/views/index.volt
templates/project/simple/views/index.phtml
templates/project/simple/views/index.volt

Hello!
* Type: update
I updated the bootstrap framework to the latest version (4.0) by updating all the css and script links.
Now when someone create a new project they will get bootstrap 4 installed (instead of version 3).
Happy coding!
Thanks

Updated Bootstrap framework from version 3.x to 4.0

---

phpstan.neon
scripts/Phalcon/Builder/Model.php

Hello!
feature: Make provision to keep constant and propertie when generating Views
Thanks

fix: Make provision to keep constant and propertie when generating Views

---

scripts/Phalcon/Migrations.php

Hello!
* Link to issue: https://github.com/phalcon/phalcon-devtools/issues/1259
Small description of change: set database connection dialect before checking the migrations table.

set database connection dialect

---

scripts/Phalcon/Builder/Scaffold.php
templates/scaffold/no-forms/views/search.phtml
templates/scaffold/no-forms/views/search.volt

Hello!
* Link to issue: #1249
Small description of change: Fixed pagination styles. Difference in screenshots below
**Before**
**After**
Thanks

#1249 - Fix bootstrap pagination

---

ide/gen-stubs.php

Hello!
* Link to issue: #1277
Example of new usage:
```sh
cd /opt
git clone git@github.com:phalcon/cphalcon.git
cd /path/to/devtools
CPHALCON_DIR=/opt/cphalcon/ext/ php ide/gen-stubs.php
```
Thanks

#1277 - Changed logic of cphalcon ext path in ide/gen-stubs.php

---

composer.json

Hello!
* Link to issue: #1284 
Due the bug in PHP 7.3.2 version, exclude that version in composer.
Thanks

#1284 - Updated requirements of PHP in composer

---

scripts/Phalcon/Builder/Model.php

all issues are in file: ```scripts/Phalcon/Builder/Model.php```
* bugfix: fixes issue #1235 
this issue occurs when creating model without using namespace it throws InvalidArgumentException when setting relations ```hasMany``` and ```belongsTo```
* bugfix: fixes issue #1286
this issue is when creating model without using namespace the ```Model::getEntityClassName``` method produces extra backslash only in belongsTo relation
example:
```php
$this->belongsTo('school_year_id', '\SchoolYear', 'school_year_id', ['alias' => 'SchoolYear']);
```
changes to ```line #183``` and ```line #201```
changed ```getOption``` method to ```hasOption```
changes to  ``` line #202``` and ``` line #210``` …

fixes for issue #1235 and issue #1286

---

scripts/Phalcon/Web/Tools/Controllers/ModelsController.php

Hello!
* Link to issue: #1234 
Added missing option `config` for model builder through webtools UI.

#1234 - [Webtools] Model generation fix

---

scripts/Phalcon/Migrations.php

Hello!
* Link to issue: #1190 
Current fix is considered as _fast hotfix_ to migrations, due deprecation/removal of migrations in 4.0.

#1190 - Migration log index size fix

---

scripts/Phalcon/Mvc/Model/Migration.php

Hello!
* Type: bug fix | code quality
* Link to issue: #1264 
Column size detection moved into separate static method and added to ignore size creation for `TEXT` column types.
Before
```
public function morph()
{
$this->morphTable('map', [
'columns' => [
new Column(
'id',
[
'type' => Column::TYPE_INTEGER,
'unsigned' => true,
'notNull' => true,
'autoIncrement' => true,
'size' => 10,
'first' => true
]
),
new Column(
'path',
[
'type' => Column::TYPE_TEXT,
'size' => 1,
'after' => 'id'
]
),
new Column(
'created_at',
[
'type' => Column::TYPE_DATETIME,
'size' => 1,
'after' => 'path'
]
)
],
'indexes' => [
new Index('PRIMARY', ['id'], 'PRIMARY'),
],
]
);
}
```
After
```
public function morph()
{ …
```

#1264 - Migration column size fix

---

scripts/Phalcon/Builder/AllModels.php
scripts/Phalcon/Builder/Model.php
tests/_data/console/app/models/files/TestModel5.php
tests/_data/schemas/mysql/dump.sql
tests/console/GenerateMultyModelsCept.php
tests/console/GenerateSingleModelCept.php
tests/unit/Builder/ModelTest.php

Hello!
* issue:
#1162
This may be a better solution than #1255 
We expect that setting --schema="" will not add `setSchema()` in `initialize()`.
**Please check if fix provides desired behaviour.  If not I'll look into fixing #1255  ^^**
---
---
- another pull request for this issue exists, but looks stale and this may be the better solution.
- this PR passes the option schema value from `AllModels::build` to `Models`.  
- we still use the schema from config to get our adapter instance
- this allows behaviour as described here: https://forum.phalconphp.com/discussion/15823/phalcon-tools-setschema-by-default-now
Thanks
[:contrib:]: https://github.com/phalcon/phalcon-devtools/blob/master/CONTRIBUTI …

fix: should not setSchema('foo') in initialize when we set --schema=""

---

.travis.yml
composer.json

Hello!
* Add PHP 7.3 to Travis
* Use latest stable version of Phalcon (v3.4.4) in Travis (but v3.4.1 will be used for PHP 5.5 because this is the latest supported version)
* Remove `cache: apt` because it's not supported (see https://github.com/travis-ci/travis-ci/issues/5876#issuecomment-207661127)
* Switch to Ubuntu Xenial instead of Trusty (but Trusty will be used for PHP 5.5)
Thanks

Add PHP 7.3 and Phalcon v3.4.4 to Travis

---

scripts/Phalcon/Commands/Builtin/Project.php

Hello!
* Link to issue: #1329
Small description of change: Set default install dir to current dir instead of '/'

Run from current dir as default instead of root. Issue #1329

---

resources/elements/sidebar-menu.php
scripts/Phalcon/Web/Tools/Views/controllers/edit.volt
scripts/Phalcon/Web/Tools/Views/controllers/generate.volt
scripts/Phalcon/Web/Tools/Views/controllers/index.volt
scripts/Phalcon/Web/Tools/Views/migrations/generate.volt
scripts/Phalcon/Web/Tools/Views/migrations/index.volt
scripts/Phalcon/Web/Tools/Views/migrations/run.volt
scripts/Phalcon/Web/Tools/Views/models/edit.volt
scripts/Phalcon/Web/Tools/Views/models/generate.volt
scripts/Phalcon/Web/Tools/Views/models/index.volt
scripts/Phalcon/Web/Tools/Views/scaffold/generate.volt
templates/project/micro/config.ini
templates/project/micro/config.php
templates/project/micro/services.php
templates/project/modules/config.ini
templates/project/modules/config.php
templates/project/modules/services_web.php
templates/project/simple/config.ini
templates/project/simple/config.php
templates/project/simple/services.php

Hello!
* Link to issue: #1305
Thanks

#1305 - Fix URL during phalcon serve

---

templates/project/simple/router.php

* Link to issue: https://github.com/phalcon/phalcon-devtools/issues/1374
The `router.php` file when running the `project` command is missing the `$_SERVER["REQUEST_URI"]` global variable in the `handle()` method as required in https://docs.phalcon.io/4.0/en/routing. I've added this variable to the `templates/project/simple/router.php` file and generated a new project with the `project` command. Error now gone and `router.php` file running as expected.

Add missing server global variable for new router

---

bootstrap/autoload.php

Hello!
* Link to issue:  #1378 
Check new path for autoload. This path is useful when you install phalcon-devtools with composer in global or local way.
If the path exists, I update the variable $vendorAutoload to load the correct file.
Thanks

Import global vendor of Composer

---

templates/project/simple/services.php

Hello!
To use Volt with Phalcon v4, I updated two Volt options :
`compiledPath` -> `path`
and
`compiledSeparator` -> `separator`
* Link to issue: #1380 
Thanks

Fix deprecated errors (compiled*)

---

src/Commands/Command.php
tests/console/GenerateProjectCept.php

Hello!
* Type: bug fix | code quality
* Link to issue: #1383
**Description:**
Some refactor to know how to and new test case, specific for the issue.
Thanks

#1383 - CLI project args

---

src/Providers/RouterProvider.php
tests/acceptance/Web/Tools/Controllers/ErrorControllerCest.php
tests/acceptance/Web/Tools/Controllers/IndexControllerCest.php

Hello!
* Link to issue: #1412
Thanks

#1412 - Fix root uri

---

src/Builder/Component/Model.php
src/Utils.php

PdoFactory uses additional 'options' key in config and lowercase adapter name.

Fix database connection using PdoFactory when creating a model

---

CHANGELOG.md
src/Builder/Project/Cli.php
templates/project/cli/launcher.bat

Hello team!
I added the launcher.bat file that missing for Windows.
I changed / to DIRECTORY_SEPARATOR.
In the launcher.bat files, I changed the name PATH to CURRENT_PATH. Windows use PATH to know where php is locate so it's very important to not override this variable.
I added a changelog, it will be useful when release a new version.
* Link to issue: #1440 
Thanks for the review :-)

fix: added cli/launcher.bat and add changelog #1440

---

src/Builder/Component/Model.php

Regenerating an existing model with `--force` duplicates camelized properties.

Fix duplicate camelCase properties

---

src/Builder/Component/Model.php
src/Builder/Path.php
src/Generator/Snippet.php

Hello team!
I fixed some errors that Psalm found.
And I resolve the problem with empty - Calling empty on a boolean value is almost certainly unintended
Thanks

Fix error Psalm - Calling empty on a boolean value is almost certainly unintended

---

CHANGELOG.md
src/Builder/Project/Simple.php
tests/console/GenerateProjectCept.php

Hello team!
By default webtools is no more activated by default.
And I made a two tests to check it.
One to check that without --enable-webtools, there are no webtools files.
With --enable-webtools, I check, if the files webtools.php and webtools.config.php are in the folder.
* Link to issue: #1410
Thanks

fix: #1410 - webtools not enabled by default

---

composer.json
phpstan.neon
src/Bootstrap.php

Changed Di instance order in Boostrap File. Was being instanciated after the App class, when it needs to be in first place to be utilised in App object.

#1471 - Fix Di instance order

---

CHANGELOG.md
src/Builder/Component/Scaffold.php
src/Generator/Snippet.php
tests/_data/console/app/models/files/TestModel.php
tests/_data/console/app/models/files/TestModel2.php
tests/_data/console/app/models/files/TestModel3.php
tests/_data/console/app/models/files/TestModel5.php
tests/_data/console/app/models/files/Testmodel4.php

Hello!
* Link to issue: #1477 
Added trailing semicolon to scaffolding crud views getters
Thanks

ISSUE-1477: Added trailing semicolon to scaffolding crud views

---

CHANGELOG.md
src/Builder/Component/Model.php
src/Builder/Component/Scaffold.php
src/Generator/Snippet.php
tests/_data/console/app/models/files/TestModel.php
tests/_data/console/app/models/files/TestModel2.php
tests/_data/console/app/models/files/TestModel3.php
tests/_data/console/app/models/files/TestModel5.php
tests/_data/console/app/models/files/Testmodel4.php

Hello!
* Link to issue: #1491 
Changed `modelOptions->getOption()` to `modelOptions->hasOption()` in conditional checks for namespace and abstract
Thanks

ISSUE-1491: Fixed optional options checks on model create

---

CHANGELOG.md
src/Builder/Component/Controller.php
src/Builder/Component/Model.php
src/Builder/Component/Scaffold.php
src/Generator/Snippet.php
tests/_data/console/app/models/files/TestModel.php
tests/_data/console/app/models/files/TestModel2.php
tests/_data/console/app/models/files/TestModel3.php
tests/_data/console/app/models/files/TestModel5.php
tests/_data/console/app/models/files/Testmodel4.php

Hello!
* Link to issue: #1297 
Removed getSource() method generation.
It became `final` in [phalcon/cphalcon#13950](https://github.com/phalcon/cphalcon/pull/13950)
Thanks

ISSUE-1297: Removed getSource() method due to final implementation

---

CHANGELOG.md
src/Builder/Component/AllModels.php
src/Builder/Component/Model.php

Hello!
* Link to issue: #1317 
Fixed constants dropping in models when recreating with `--force` option: constants with access modifiers (public, protected, private) were ignored by preg_match pattern.
Fixed attributes duplication bug when recreating with `--force` option if no `--camelize` option declared and property is snake_cased.
Fixed column mapping on creation from table with PascalCase fields.
Thanks

ISSUE-1317: Fix model --force creation bugs

---

scripts/Phalcon/Builder/AllModels.php
scripts/Phalcon/Builder/Controller.php
scripts/Phalcon/Builder/Module.php
scripts/Phalcon/Builder/Project.php

Hello!
* Link to issue: https://github.com/phalcon/phalcon-devtools/issues/1506
Fixes issue where
```
phalcon create-controller --name test
```
defaults to NULL as the directory where it searches for the config.php file in the wrong place, `/`, upon not finding it, the code falls back to a recursive directory search logic which then finds the `public/webtools.config.php` file and loads up the wrong config file causing an error:
> PHP Fatal error:  Uncaught Error: Call to a member function path() on int in /var/www/repos/phalcon-devtools/scripts/Phalcon/Builder/Controller.php:74
Stack trace:
#0 /var/www/repos/phalcon-devtools/scripts/Phalcon/Commands/Builtin/Controlle …

Fix #1506 config file locating issue

---

phalcon
scripts/Phalcon/Builder/Model.php
scripts/Phalcon/Exception/Db/PDODriverNotFoundException.php

Hello!
* Link to issue: https://github.com/phalcon/phalcon-devtools/issues/1479
If using a PDO driver such as Postgresql or Mysql, and it is not loaded when trying to go through the Phalcon adapter, PDO will error with the vague "could not find driver" which will leave developers on a quest to figure out what happened.
This PR will fix the vague issue for 3.4.x and it will instead show a much more detailed error.
Thanks

Fix #1479 more verbose pdo driver missing errors for 3.4.x

---

phalcon
src/Builder/Component/Model.php
src/Exception/PDODriverNotFoundException.php

Hello!
* Link to issue: https://github.com/phalcon/phalcon-devtools/issues/1479
If using a PDO driver such as Postgresql or Mysql, and it is not loaded when trying to go through the Phalcon adapter, PDO will error with the vague "could not find driver" which will leave developers on a quest to figure out what happened.
This PR will fix the vague issue for 4.0.x and it will instead show a much more detailed error.
Thanks

Fix #1479 more verbose pdo driver missing errors for 4.0.x

---

phalcon
src/Builder/Component/Model.php
src/Exception/PDODriverNotFoundException.php

Hello!
* Link to issue: https://github.com/phalcon/phalcon-devtools/issues/1479
If using a PDO driver such as Postgresql or Mysql, and it is not loaded when trying to go through the Phalcon adapter, PDO will error with the vague "could not find driver" which will leave developers on a quest to figure out what happened.
This PR will fix the vague issue for 4.1.x and it will instead show a much more detailed error.
Thanks

Fix #1479 more verbose pdo driver missing errors for 4.1.x

---

src/Version.php

Hello!
* Link to issue: https://github.com/phalcon/phalcon-devtools/issues/1508
4.0.x uses _getVersion() instead of getVersion() when extending Phacon\Version,
this results in devtools reporting back the wrong version of devtools back to the user as though devtools and phalcon have the same version when they really have different versions.
Thanks

Fix #1508 devtools version showing phalcon version instead for 4.0.x

---

src/Version.php

Hello!
* Link to issue: https://github.com/phalcon/phalcon-devtools/issues/1508
4.1.x uses _getVersion() instead of getVersion() when extending Phacon\Version,
this results in devtools reporting back the wrong version of devtools to the user as though devtools and phalcon have the same version when they really have different versions.
Thanks

Fix #1508 devtools version showing phalcon version instead for 4.1.x
